- hosts: all
  gather_facts: false
  become: true
  vars:
  - msg: "welcome all"
  pre_tasks:
  - name: install python
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    tags: run2
  tasks:
  - name: add nginx repo
    apt_repository: repo='ppa:nginx/stable' state=present
    register: ppastable
    tags: [run, run2]
  - name: debug
    debug:
      var: ppastable
    tags: run
  - name: debug
    debug:
      msg: "ppastate {{ ppastable.state }}"
#  - name: debug with when
#    debug:
#      msg: "ppastate {{ ppastable.state }}"
#      when: ppastable.failed is true
  - name: nginx install
    apt: pkg=nginx state=present update_cache=true
    when: ppastable is success
    register: nginxinstallstatus
    notify:
      - start nginx   
  - name: index.html copy
    when: nginxinstallstatus is success
    template: src=index.html.j2 dest=/var/www/html/index.nginx-debian.html
    notify:
      - start nginx  
  handlers:
    - name: start nginx
      service: name=nginx state=started 
