---
# tasks file for webserver
- name: installing apache2
  apt: name=apache2 state=latest
  become: true
  notify:
    restart_apache2
- name: file creation index2.html
  file: path=/var/www/html/index2.html state=touch mode="u=rwx,g=rwx,o=rwx"
  become: true
- name: change cofig at /var/www/html/index2.html. Create a backup file including the timestamp information so you can get the original file back if you somehow clobbered it incorrectly.
  copy: src=index2.html dest=/var/www/html/index2.html
  backup: yes
  become: true
- name: Basic Template Example
  template:
    src: example1.j2
    dest: /var/www/html/index.html
  become: true
  notify:
    restart_apache2
- name:This module works like copy, but in reverse. It is used for fetching files from remote machines and storing them locally in a file tree, organized by hostname.
  fetch:
    src: /var/www/html/index.html
    dest: /tmp/prefix-{{ inventory_hostname }}
    flat: yes
- name: template loop example
  template: src=example2.j2 dest=/var/www/html/index3.html
  become: true
  notify:
    restart_apache2
- name: template loop example
  template: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
  with_items:
    - {src: 'exam.j2', dest: /var/www/html/exam.html}
    - {src: 'exam1.j2', dest: /var/www/html/exam1.html}
  become: true
  notify:
    restart_apache2
