---
# tasks file for common
- name: Add OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: install NTP
  yum: name=ntp state={{ ntp_status }}
  when: ansible_os_family == 'RedHat'
  debug:
    var: ntp_status

- name: install NTP
  yum: name=ntp state={{ ntp_status }}
  when: ansible_os_family == 'Ubuntu' and ansible_distribution_version == '16.04'
  debug:
    var: ntp_status
