---
# tasks file for webserver
- name: installing apache2
  apt: name=apache2 state=latest
  become: true
  notify:
    restart_apache2
- name: file creation index2.html
  file: path=/var/www/html/index2.html state=touch mode="u=rwx,g=rwx,o=rwx"
  become: true
- name: change cofig at /var/www/html/index2.html
  copy: src=index2.html dest=/var/www/html/index2.html
  become: true
- name: Basic Template Example
  template:
    src: example1.j2
    dest: /var/www/html/index.html
  become: true
  notify:
    restart_apache2  
