---
# tasks file for webserver
- name: installing apache2
  apt: name=apache2 state=latest
  become: true
  notify:
    restart_apache2
#- name: change cofig at /var/www/html/index.html
#  copy: src=index.html dest=/var/www/html/index.html
#  become: true
- name: Basic Template Example
  template:
    src: example1.j2
    dest: /var/www/html/index.html
  become: true
  notify:
    restart_apache2  
